### ISSUE TITLE
请问是否可以支持没有属性的列表

### ISSUE THREAD

**Issue by bemofan** [sethyuan/logseq-plugin-kanban-board#1]
大佬，非常喜欢您的插件，如果可以支持没有属性的列表那可太好了。如果可以去除背景色和那就完美了。非常感谢

**Comment by sethyuan** [comment]
我试了一下没有背景色的，好像也不错。没有属性的列表是什么意思？使用指定属性来构建看板是为了把看板的不同列表作为数据的不同状态来展现，例如一个任务在“未开始”，“进行中”，“已完成”等状态之前切换。

**Comment by CodingXCat** [comment]
个人理解是不是说TODO那种前缀tag开头的，这样就可以和TODO系统集成，不用通过改变属性来改变列

**Comment by sethyuan** [comment]
好的，我在你另一个ticket里回复了。背景色的已经改了发布了，这个ticket我就先关了。
