### ISSUE TITLE
Please add an ability to hide tags from query type kanban view

### ISSUE THREAD

**Issue by stan-voo** [sethyuan/logseq-plugin-kanban-board#10]
Please add an ability to hide tags from query type kanban view: 
![💚 Skills 2023-08-03 at 12 10 49 PM](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/9213607/d93a46eb-b9b0-4382-ab5f-bc99779c2f60)

**Comment by sethyuan** [comment]
@stan-voo , `tags` is now hidden, and the tags listed in it are expressed as card tags now.
