### ISSUE TITLE
Feature Request: Ability to include block results without column property into new "Blank" column (for kboard-query)

### ISSUE THREAD

**Issue by bluckholl** [sethyuan/logseq-plugin-kanban-board#11]
Motivation:
Get kanban work immediately without prepare in advance block properties and values, 
so all blocks in query results with an empty property (property not exists / have an empty value) will appears in the first new "Blank" column.

use-case for example:
I have a query for all tasks that scheduled / deadline in the next 14 days,
and want to tag them with new property "goal" with values Today / This Week / Near Future
This feature will show all tasks without "goal" in Kanban and allow to drag it to other columns.

I love your plugins, you are doing really great job!

**Comment by sethyuan** [comment]
Thanks!

My understanding of your use case (if I'm not wrong) is that you still need to specify "goal" as the property, and "Today", "This Week" and "Near Future" as the values, and on top of that, those blocks from the query result that have no property "goal" will be listed in a special column, say `(ungrouped)`, so you will effectively have 4 columns in total.

This is great idea, I'll look into it.

**Comment by bluckholl** [comment]
Exactly!
❤️

**Comment by sethyuan** [comment]
@bluckholl , this is implemented.

**Comment by sethyuan** [comment]
Sorting by due dates is a very special case, let me think about it.

**Comment by sethyuan** [comment]
@bluckholl It's implemented. The results will be sorted first by due dates if there is any, then by content alphabetically.

**Comment by bluckholl** [comment]
You are correct, due date is a special case (even here we have two different dates to refer to schedule and deadline) - that's why I thought here to embrace query sorting - as with advance queries, different kind of sorting can be implemented (e.g. Calculation of due date days and task importance) 
So the results order can be display according to that order.

This is really nice to have,
Due dates sorting is already full fill main scenario.

I'm appreciate your contribution, thanks a lot
(sent you some coffees you definitely deserved ;) )

**Comment by sethyuan** [comment]
@bluckholl Thank you for the recognition! ☀️

**Comment by bluckholl** [comment]
I probably missing something, as it still sorting by name although I installed new version (also clean cache)
e.g. 
- {{renderer :kboard-query, focus, focuscategory, Today, Tomorrow}}
configs:: {"tagColors":{"workitem_needed":"e60ce7"}}
   - {{query (property :focuscategory)}}

![image](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/2509820/3b695db7-0f97-4c50-bcef-ce297159c120)
- [#A] a test
  focuscategory::
- [#A] b test with schedule today
  SCHEDULED: <2023-08-08 Tue>  
  focuscategory::

Oh, now I tried to add another example for tomorrow and yesterday, and I see there are no cards shown, probably due to this exception:

![image](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/2509820/7541c1c1-d2b0-4442-b022-e84e8dc727bf)

Here are all the blocks to reproduce:

- {{renderer :kboard-query, focus, focuscategory, Today, Tomorrow}}
configs:: {"tagColors":{"workitem_needed":"e60ce7"}}
   - {{query (property :focuscategory)}}

- [#A] a test
  focuscategory::
- [#A] b test with schedule today
  SCHEDULED: <2023-08-08 Tue>  
  focuscategory::
- [#A] c test with schedule yesterday
  SCHEDULED: <2023-08-07 Mon>  
  focuscategory::
- [#A] d test with scheedule tomorrow
  SCHEDULED: <2023-08-09 Wed>  
  focuscategory::

**Comment by sethyuan** [comment]
Sorry, there is a bug with scheduled/deadline date handling, I'll look into it.

**Comment by bluckholl** [comment]
It works great, thank you!!
