### ISSUE TITLE
Issue with advanced Queries

### ISSUE THREAD

**Issue by ie98alka** [sethyuan/logseq-plugin-kanban-board#14]
There seems to be a  problem with advanced queries when adding and using ":inputs". For some reason this does not work but if you remove the commented lines in the query it does work.

- TODO Test
  SCHEDULED: <2023-09-21 Thu>  
  duration:: {"TODO":[0,1695300128748],"DOING":[0,1695300326195]}
- TODO Test2
  duration:: {"TODO":[0,1695365749844]}
  SCHEDULED: <2023-09-22 Fri>  
- {{renderer(:kboard-marker-query,Kanban,TODO,DOING,DONE,cover,260px)}}
	- #+BEGIN_QUERY
         {:title [:h3 "✅ Planned"]
        :query [:find (pull ?b [*])
         :in $ ?page ; Remove this along with the other commented lines and kanban works
        :where
        [?b :block/marker ?marker]
   [(contains? #{"TODO" "LATER"} ?marker)] 
   [?b :block/scheduled ?d] 
  [?p :block/name ?page] ; Remove
 ]
:inputs [:query-page]; Remove
 :result-transform (fn [result] (sort-by (fn [r] (get-in r [:block/scheduled])) result)) ; sort the result by the scheduled date
 :table-view? false
 :breadcrumb-show? false  
 :collapsed? false
}
#+END_QUERY

**Comment by sethyuan** [comment]
The plugin SDK does not support `:inputs` nor other parts like `:result-transform` you see normally in Logseq. You must get rid of `:inputs`.
