### ISSUE TITLE
Tags are not split

### ISSUE THREAD

**Issue by almereyda** [sethyuan/logseq-plugin-kanban-board#16]
When delimiting `tags::` with a comma (`,`), they are not displayed as separate entities.

![grafik](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/60054610-26c0-487b-bcc4-a060e0fa01da)

![grafik](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/6b21698b-2a38-4ea5-91fd-603420053eba)

This may be due to an uncommon character `，` used in the split rule, and missing square brackets to indicate the characters as equally valid matches:

https://github.com/sethyuan/logseq-plugin-kanban-board/blob/748ca1a7a29c210c38cab8c97f892995bea8e98e/src/libs/utils.js#L21

The suggestion is to add the square brackets and a space character:

```diff
<    for (const t of tagsPropValue.split(/,，/)) {
>    for (const t of tagsPropValue.split(/[,， ]/)) {
```

I'm testing this with a local build, before PRing.

**Comment by sethyuan** [comment]
Yes you're right. Thanks for spotting this bug! I can fix this right now, or I can wait for your PR.

**Comment by almereyda** [comment]
@sethyuan There it is. I tried to keep it minimal, but needed to test locally first. Where I found the need for an additional `.filter()`, so this was a good step to validate and not commit blindly. The missing square bracke

**Comment by sethyuan** [comment]
It seems that there is an extra space character in the PR's regex, I removed it, FYI. A new version is released.

**Comment by almereyda** [comment]
Thank you for the quick reaction!

I fear it's needed, else the space is prepended to the next tag:

Before | After
--- | ---
![grafik](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/28528b6d-f542-46fc-a71f-ed128e214c45) | ![grafik](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/466ea676-81aa-413c-b86a-dcd95bb98fed)

![grafik](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/76f77798-1014-4f55-b0ad-cc6205a5d38b)

Do you see the little shift?

**Comment by sethyuan** [comment]
Oh, I see, let me deal with it.

**Comment by almereyda** [comment]
@sethyuan Out of curiosity, may I asked why you are using the `，` character as separator?

It seems unusual in European contexts, and VS Code warns about it, but I don't if it is actually used somewhere in the rest of the world, why I am asking.

**Comment by sethyuan** [comment]
Sure, it is the Chinese full-width comma character. I added this so that Chinese users can keep typing comma without switching the IME first.

**Comment by almereyda** [comment]
Very good!
