### ISSUE TITLE
Tag colors are recomputed when renaming a board

### ISSUE THREAD

**Issue by almereyda** [sethyuan/logseq-plugin-kanban-board#18]
**Observed behaviour**

When a board is renamed, all its associated tag colors are reevaluated.

**Expected behaviour**

Tag colors remain as they are.

**Screenshots**

Before | Click on title to edit | Edit and press Enter | After
--- | --- | --- | ---
![Bildschirmfoto vom 2023-11-15 02-28-17](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/954561b6-22ef-450e-9ff1-c54c40053b33) | ![Bildschirmfoto vom 2023-11-15 02-28-32](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/fb8b09b2-f557-4015-8d50-c880c8a9b7ed) | ![Bildschirmfoto vom 2023-11-15 02-28-40](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/48a6cbba-e02a-4d71-a496-fe7e89e31378) | ![Bildschirmfoto vom 2023-11-15 02-28-46](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/3146c638-cc10-42d9-8c1f-f1661df1a0b3)

This does not happen when editing the board title in the block.

Before | Click on block to edit | Edit and press Esc | After
--- | --- | --- | ---
![Bildschirmfoto vom 2023-11-15 02-28-46](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/3146c638-cc10-42d9-8c1f-f1661df1a0b3) | ![Bildschirmfoto vom 2023-11-15 02-31-24](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/ca1f75ca-37d5-4dc1-8175-ce8a8a1b55d0) | ![Bildschirmfoto vom 2023-11-15 02-31-32](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/7deded22-77d2-4766-bf98-661dba6fb34e) | ![Bildschirmfoto vom 2023-11-15 02-31-50](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/6b6149f0-2e32-49a3-a3da-68b14e679188)

Please note that the title of the board will update in near-real time when editing the block.

**Comment by almereyda** [comment]
After the previous example with two tags showed the color of the primary tag as stable, it also changed (and got reassigned to another tag) when three tags were present.

| Point in time | Image |
| --- | --- |
| Before | ![Bildschirmfoto vom 2023-11-15 02-36-16](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/c9d5684d-6816-4359-ba8f-617c1a8de1bf) |
| After | ![grafik](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/1645308/7451cc7e-4863-45f0-b2cf-48056b869e7a) |

It is a bit funny, but seems to defeat the purpose.

**Comment by sethyuan** [comment]
I'll investigate.

**Comment by sethyuan** [comment]
This is fixed, a new version is released. Also, the tag spacing issue is also fixed and released.

**Comment by almereyda** [comment]
Very well received. Thanks for the prompt intervention.

Verified locally with v1.17.8
