### ISSUE TITLE
Filter input fields do not receive input

### ISSUE THREAD

**Issue by almereyda** [sethyuan/logseq-plugin-kanban-board#19]
When editing a query boards filters, I can click into the input boxes, but no text is received when typing.

Should I investigate this, or would you have an idea, in case that reproduces locally with you?

**Comment by almereyda** [comment]
The workaround is to modify the query below, and to use the reload button then.

**Comment by sethyuan** [comment]
I tried a query board with my data and it looked correct, the inputs were responsive and functional. It'd be a lot help if you can help investigate when or how this happens.

**Comment by almereyda** [comment]
OK, let me see. Might take a while until I come back here.

**Comment by almereyda** [comment]
There's more. Will collect for a time, PR where possible, and report back then.

**Comment by sethyuan** [comment]
@almereyda Any inputs on this? Otherwise I'm going to close it.

**Comment by almereyda** [comment]
Sorry, yes. No, not now.
