### ISSUE TITLE
请问将来是否能够支持query呢？

### ISSUE THREAD

**Issue by CodingXCat** [sethyuan/logseq-plugin-kanban-board#2]
大佬，非常喜欢您的插件，请问将来有计划支持query么？
比如可以query出来todo list，然后在kanban里进行编辑和拖动来改变todo的状态。

**Comment by CodingXCat** [comment]
功能类似于这个https://github.com/hkgnp/logseq-kanban-plugin，但它不支持编辑和拖动，只能查看。

**Comment by sethyuan** [comment]
对于TODO的特殊支持将来可以考虑，可能会优先做看板的一些其它功能。

**Comment by saccohuo** [comment]
+1，query  task属于最直观是使用方式

**Comment by sethyuan** [comment]
@saccohuo 比较好奇，查询出的todo通过拖拽变换状态这个可以理解，但是卡片之间的顺序关系在这种情况下表达了啥呢？或者说该如何处理？

**Comment by saccohuo** [comment]
> @saccohuo 比较好奇，查询出的todo通过拖拽变换状态这个可以理解，但是卡片之间的顺序关系在这种情况下表达了啥呢？或者说该如何处理？

@sethyuan 这条我没想过，同层级卡片之间的顺序关系是不是可以没有含义，只有需要sort的时候再有意义。如果分层级的话，是不是可以用层级表示子任务？

**Comment by sethyuan** [comment]
实现了对task query的支持，在README里第3个演示视频有演示。
