### ISSUE TITLE
能否把看板之外的block放进去？

### ISSUE THREAD

**Issue by hotwow** [sethyuan/logseq-plugin-kanban-board#3]
1、看板外，剪切block再粘贴进去，并不会自动打上看板的属性
2、最好支持把看板之外的block拖进去功能
3、看板能够显示在每天的日志里

**Comment by sethyuan** [comment]
第3点估计做不了，建议把带看板的页面加入收藏？

**Comment by sethyuan** [comment]
@hotwow 这里的拖块进看板，是想要把之前的块移动过来并添加列表属性吗？
