### ISSUE TITLE
Improved support for block refs

### ISSUE THREAD

**Issue by spasm** [sethyuan/logseq-plugin-kanban-board#4]
Blockrefs appear to work, however some strange artifacts end up appended to the end of the block once it's rendered as a card:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/10431596/228392658-34c2c87d-16cb-436c-b25d-cc8431d063bd.png">

Great plugin! 🎉

**Comment by sethyuan** [comment]
Thanks for reporting this, it is now fixed, please check the new version.
