### ISSUE TITLE
请问时候可以支持一个内容同时在两个分组列表中展示

### ISSUE THREAD

**Issue by bemofan** [sethyuan/logseq-plugin-kanban-board#5]
例如硬拉，可以在臀部列表中，也可以在腿部列表。如果能支持这种格式那简直是太棒了！
最后非常感谢您的插件，祝您生活愉快，家庭幸福。

**Comment by Jackson-horse** [comment]
不是可以block reference来解决这个场景么

**Comment by sethyuan** [comment]
@bemofan 这样的用法不符合插件的理念，看板中的每个列表实际上代表了一种临时状态，卡片在任一时间对应一种且只有一种状态。你的这个场景并不是卡片的状态变化，所以不能用列表实现，应当是使用标签来实现。一个卡片可以有多个标签。
