### ISSUE TITLE
Allowing for percentage width of boards [enhancement]

### ISSUE THREAD

**Issue by ecodiv** [sethyuan/logseq-plugin-kanban-board#7]
For kanban boards with few boards, it would be great if they could fill up the full width of the page. Request therefore is to make it possible to:

1. be able to define the width of the panels
2. be able to define the width of the panels in percentages of page width.

**Comment by sethyuan** [comment]
This feature is implemented. Use it like this:

```
{{renderer :kboard, ((board block ref)), list, cover, 49%}}
```

You could also specify the width in pixels:

```
{{renderer :kboard, ((board block ref)), list, cover, 300px}}
```

**Comment by ecodiv** [comment]
I am impressed, thanks!
