### ISSUE TITLE
Can't reorder lanes

### ISSUE THREAD

**Issue by flegfleg** [sethyuan/logseq-plugin-kanban-board#8]
Hi, thanks for the plugin! 
I read that it's possible to drag an drop to reorder the "lanes" but that does not work for me (see attached video). 
Am i Missing something? 

Logseq Version 0.9.9 (0.9.9), macOS Ventura.

https://github.com/sethyuan/logseq-plugin-kanban-board/assets/4009931/1776c746-48fe-4d4d-8763-83d4a3bdc22c

**Comment by sethyuan** [comment]
What kind of board is it? Query board? Task Query board? or a normal board?

Currently, only a normal board can have lanes dragged. For a task query board, the lanes are ordered by their written order, e.g. in `{{renderer :kboard-marker-query, Kanban, LATER, NOW, DONE}}`, the order is LATER, NOW and DONE.

**Comment by flegfleg** [comment]
Hi, thanks for your answer! 

This is what i am using: 

``` 
- {{renderer :kboard-query, Fulfillmentcenter, status}}
	- {{query (and (namespace [[song]] ) (property :status))}}
	  query-table:: true
	  collapsed:: true
```

I am not sure if that is a "normal board"

**Comment by sethyuan** [comment]
I see, what you have is a query board. It is not possible to reorder the lanes for a query board now, but I'll keep it in mind, maybe I can do something about it later when I have more spare time.

BTW, a normal board is a board you create using the following 2 options:

![image](https://github.com/sethyuan/logseq-plugin-kanban-board/assets/3410293/8f759e7e-ce88-4259-91e6-8655c34dd4c0)

All of its data is based on a root block and it has the most complete features the plugin offers.

**Comment by flegfleg** [comment]
Ah, OK! It would be great if you could implement reordering queries.

**Comment by sethyuan** [comment]
@flegfleg It's implemented, please try the new version.

**Comment by flegfleg** [comment]
Thanks! Amazing!
