### ISSUE TITLE
这个插件太好了，体验上比市场上另一款看板插件好太多了

### ISSUE THREAD

**Issue by b-yp** [sethyuan/logseq-plugin-kanban-board#9]
目前拖动卡片的时候拖到 “添加一张卡片” 按钮的上方才能生效，想问一下能不能支持拖到整个列的任何一个地方就可以生效的（就像 jira 一样），还是说做成这样有什么其他方面的考量

**Comment by sethyuan** [comment]
谢谢你的评价！看板的卡片之间存在顺序关系，添加按钮是不参与卡片的排序的，所以将卡片拖到添加按钮下方是说不通的，而且在技术实现上也不太方便。

**Comment by b-yp** [comment]
好的，明白了大佬，感谢大佬回复&nbsp;🤗


---原始邮件---
发件人: &quot;Seth ***@***.***&gt;
发送时间: 2023年7月4日(周二) 上午8:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sethyuan/logseq-plugin-kanban-board] 这个插件太好了，体验上比市场上另一款看板插件好太多了 (Issue #9)




 
谢谢你的评价！看板的卡片之间存在顺序关系，添加按钮是不参与卡片的排序的，所以将卡片拖到添加按钮下方是说不通的，而且在技术实现上也不太方便。
 
&mdash;
